"""empty message

Revision ID: d971b343d84d
Revises: 
Create Date: 2021-05-10 12:26:24.713603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd971b343d84d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('imageURL', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('danger', sa.Integer(), nullable=False),
    sa.Column('endDate', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('startLat', sa.Float(), nullable=True),
    sa.Column('startLong', sa.Float(), nullable=True),
    sa.Column('endLat', sa.Float(), nullable=True),
    sa.Column('endLong', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clockId', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(length=100), nullable=True),
    sa.Column('water', sa.String(length=100), nullable=True),
    sa.Column('temp', sa.String(length=100), nullable=True),
    sa.Column('shelter', sa.String(length=100), nullable=True),
    sa.Column('tools', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['clockId'], ['clocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplies')
    op.drop_table('follows')
    op.drop_table('clocks')
    op.drop_table('users')
    # ### end Alembic commands ###
